SAVMS:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    #设置jwt签名加密是使用的密钥
    user-secret-key: itheima
    #设置jwt过期时间
    user-ttl: 7200000
    #设置前端传递过来的令牌名称
    user-token-name: authentication
